--- #YAML:1.0
name:                Config-Options
version:             0.02
abstract:            Blessed hash for options
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Data::Dumper:                  2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
