# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Options
version:      0.03
version_from: lib/Config/Options.pm
installdirs:  site
requires:
    Data::Dumper:                  2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
